Repository pylast/pylast, pull requests merged in 2021-11, with the labels that each got.

#375 Replace deprecated pypy3 with pypy-3.8
  .github/workflows/test.yml
  tests/test_network.py
Labels: test, changelog: skip

#376 Convert setup.py to static setup.cfg and format with setup-cfg-fmt
  .editorconfig
  .github/release-drafter.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  setup.cfg
  setup.py
Labels: changelog: Changed

#377 Speedup: Use faster `importlib.metadata` for getting version
  setup.cfg
  src/pylast/__init__.py
Labels: changelog: Changed

#367 Set `get_top_tracks` limit even if it's `None`, to get unlimited user `top_tracks`
  src/pylast/__init__.py
Labels: changelog: Fixed
