Repository pylast/pylast, pull requests merged in 2025-03, with the labels that each got.

#477 Double read timeout to fix 'The read operation timed out'
  src/pylast/__init__.py
Labels: changelog: Fixed

#478 Update types and run mypy on GitHub Actions
  .coveragerc
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  requirements-mypy.txt
  src/pylast/__init__.py
  tox.ini
Labels: changelog: Changed

#476 Define project as typed to allow tools to use the provided typing
  pyproject.toml
  src/pylast/py.typed
Labels: changelog: Added
